version: "3.7"

services: 
  backend:
    build: 
      context: ../backend/
      dockerfile: ../containers/backend/Dockerfile.dev
    image: bruni-backend:dev
    container_name: bruni-backend-dev
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes: 
      - ../backend/:/usr/src/app
    networks: 
      - bruni-network

  webserver:
    image: nginx:alpine
    container_name: bruni-webserver
    restart: unless-stopped
    ports: 
      - 8000:80
    volumes: 
      - ./webserver/conf.d/:/etc/nginx/conf.d
    networks: 
      - bruni-network
    depends_on: 
      - backend

  database:
    image: mongo:5
    container_name: bruni-database
    environment: 
      MONGO_INITDB_ROOT_USERNAME: kenji
      MONGO_INITDB_ROOT_PASSWORD: kenji-X456UR
    volumes: 
      - mongo-data:/data/db
  
networks: 
  bruni-network:
    driver: bridge

volumes: 
  mongo-data: